import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class DsSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form DsLop
     */
    public DsSinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtCMND = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableLop = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbxMalop = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtImport = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtGender = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh Sách Lớp");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel2.setText("MSSV:");

        jLabel3.setText("Họ Tên:");

        jLabel5.setText("CMND:");

        tableLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Họ Tên", "Giới Tính", "CMND"
            }
        ));
        jScrollPane1.setViewportView(tableLop);
        if (tableLop.getColumnModel().getColumnCount() > 0) {
            tableLop.getColumnModel().getColumn(0).setResizable(false);
            tableLop.getColumnModel().getColumn(3).setResizable(false);
        }

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Reset");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        jLabel6.setText("Mã lớp:");

        cbxMalop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Chọn mã lớp-", "17HCB", "18HCB" }));
        cbxMalop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMalopActionPerformed(evt);
            }
        });

        jLabel7.setText("Import:");

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImportActionPerformed(evt);
            }
        });

        jLabel1.setText("Giới Tính:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 255));
        jLabel8.setText("QUẢN LÍ DANH SÁCH SINH VIÊN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnThoat)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGender))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel5))
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbxMalop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMSSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtImport, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnXoa))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnThoat)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
        this.dispose();
    }//GEN-LAST:event_btnThoatActionPerformed

    private void cbxMalopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMalopActionPerformed
        // TODO add your handling code here:
        Danhsachlop ds = new Danhsachlop();
        //ds.setMaLop(cbxMalop.getSelectedItem().toString());
        if(cbxMalop.getSelectedItem().toString() == "17HCB")
        {
            reloadData();
            String filePath = "C:\\Users\\user\\Documents\\NetBeansProjects\\BTQLSV\\docs\\17HCB.csv";
            File file = new File(filePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String [] columsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)tableLop.getModel();
            model.setColumnIdentifiers(columsName);
            
            Object [] tableLines = br.lines().toArray();
            for(int i =0; i< tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String [] dataRow = line.split(",");
                model.addRow(dataRow);
            }

                
        } catch (Exception ex) {
            Logger.getLogger(DsSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        }else if(cbxMalop.getSelectedItem().toString() == "18HCB")
        {
            reloadData();
            String filePath = "C:\\Users\\user\\Documents\\NetBeansProjects\\BTQLSV\\docs\\18HCB.csv";
            File file = new File(filePath);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
            String firstLine = br.readLine().trim();
            String [] columsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)tableLop.getModel();
            model.setColumnIdentifiers(columsName);
            
            Object [] tableLines = br.lines().toArray();
            for(int i =0; i< tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String [] dataRow = line.split(",");
                model.addRow(dataRow);
            }

                
        } catch (Exception ex) {
            Logger.getLogger(DsSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_cbxMalopActionPerformed

//    //Get Last Line text of File
//    public String getlastLine(BufferedReader br){
//        try{
//            String sCurrentLine = "";
//            String lastLine = "";
//
//            while ((sCurrentLine = br.readLine()) != null) 
//            {
//                System.out.println(sCurrentLine);
//                lastLine = sCurrentLine;
//            }
//            return lastLine;
//        }catch(IOException evt){
//            System.out.print("EROR getlastLine");
//        }
//        
//        return "";
//    }
    
    //Get Current STT
    public int getCurrentSTT(String lastLine){
       // String lastLine = getlastLine(br);
        if (lastLine != ""){
           String[] arr =  lastLine.split(",");
           return Integer.parseInt(arr[0]) + 1;
        }
        
        return 0;
    }
    
    List<Danhsachlop> list = new ArrayList<Danhsachlop>();
    String gender = "";
    
    //THEM DU LIEU
    public void ThemDuLieuVaoList()
    {
        Danhsachlop ds = new Danhsachlop();
        //ds.setMaLop(cbxMalop.getSelectedItem().toString());
        ds.setMSSV(txtMSSV.getText().toString());
        ds.setHoTen(txtHoTen.getText().toString());
        ds.setGioiTinh(txtGender.getText().toString());
        ds.setCMND(Integer.valueOf(txtMSSV.getText().toString()));
        
        /*if (radioNam.isSelected()==true){
            ds.setGioiTinh("Nam");
            gender = "Nam";
        }else{
            if (radioNu.isSelected() == true){
                ds.setGioiTinh("Nữ");
                gender = "Nu";
            }
        }*/
                
        //ds.setGioiTinh(buttonGroup1.getSelection().toString());
        //System.out.print(buttonGroup1.getSelection());
        
//        String info = txtMSSV.getText().toString() +"," 
//                + txtHoTen.getText().toString() + "," 
//                + gender + ","
//                + txtCMND.getText().toString();
        
        try{
            
            System.out.print(selectedPath);
            
             FileWriter pw = new FileWriter(selectedPath, true);
             pw.append("\n");
             
             pw.append(Integer.toString(currentSTT));
             pw.append(", ");
             
             pw.append(txtMSSV.getText().toString());
             pw.append(", ");
             
             pw.append(txtHoTen.getText().toString());
             pw.append(", "); 
             
             pw.append(txtGender.getText().toString());
             pw.append(", ");  
             
             pw.append(txtCMND.getText().toString());
             pw.append(", "); 
             //pw.flush();
             pw.close();
             
             currentSTT +=1;
            
        }catch(IOException e){
            System.out.print(e.getMessage());
        }
      
     
    }
    public void fillDatatoTable()
    {
        DefaultTableModel model = (DefaultTableModel)tableLop.getModel();
        model.setRowCount(0);
        for(Danhsachlop ds: list)
        {
            Object[] obj = new Object[]{ds.MaLop, ds.MSSV, ds.HoTen, ds.GioiTinh, ds.CMND};
            model.addRow(obj);
        }
    }
    
    public void reloadData()
    {
        DefaultTableModel model = (DefaultTableModel)tableLop.getModel();
        model.setRowCount(0);
        for(Danhsachlop ds: list)
        {
            Object[] obj = new Object[]{"", "", "", "", ""};
            model.addRow(obj);
        }
    }
    
    public void ghi(ArrayList<Danhsachlop> List){
        try {PrintWriter pw = new PrintWriter(new File("C:\\Users\\user\\Documents\\NetBeansProjects\\BTQLSV\\docs\\17HCB.csv"));
            for(Danhsachlop ds: list){
                pw.print(ds.getMSSV());
                pw.print(ds.getHoTen());
                pw.print(ds.getGioiTinh());
                pw.print(ds.getCMND());
            }
        } catch (Exception e) {
            System.out.println("Got an exception!");
        }
    }
    
    public ArrayList docDslop(String filePath){
        ArrayList<Danhsachlop> list = new ArrayList<>();
//        try (Scanner sc = new Scanner(new File("C:\\Users\\user\\Documents\\NetBeansProjects\\BTQLSV\\docs\\17HCB.csv"))){
            try (Scanner sc = new Scanner(new File(filePath))){
            while(sc.hasNext()){
                Danhsachlop ds = new Danhsachlop();
                ds.setMSSV(sc.next());
                ds.setHoTen(sc.next());
                ds.setGioiTinh(sc.next());
                ds.setCMND(Integer.parseInt(sc.next()));
                
                list.add(ds);
            }
        } catch (Exception e) {
            System.out.println("Got an exception!");
        }
        return list;
    }
            
    
    
    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
      ThemDuLieuVaoList();
      //fillDatatoTable();
      //
       
        try {
            File file = new File(selectedFileName);
            BufferedReader br = new BufferedReader(new FileReader(file));
            
            String firstLine = br.readLine().trim();
            String [] columsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)tableLop.getModel();
            for (int i = model.getRowCount() - 1; i> -1;i--){
                model.removeRow(i);
            }
            
            model.setColumnIdentifiers(columsName);
            
            Object [] tableLines = br.lines().toArray();
            for(int i =0; i< tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String [] dataRow = line.split(",");
                model.addRow(dataRow);
            }
            
//            //Get Last line
//            if (tableLines.length > 1){
//                int numLines = tableLines.length;
//                currentSTT = getCurrentSTT(tableLines[numLines-1].toString());
//            }else{
//                currentSTT = 0;
//            }

                
        } catch (Exception ex) {
            Logger.getLogger(DsSinhVien.class.getName()).log(Level.SEVERE, null, ex);
            
        }
       
    }//GEN-LAST:event_btnThemActionPerformed

    private void clear()
    {
        txtMSSV.setText("");
        txtHoTen.setText("");
        txtGender.setText("");
        txtCMND.setText("");
        txtImport.setText("");
    }
    
            
    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnXoaActionPerformed

    
    String selectedPath = "";
    String selectedFileName = "";
    int currentSTT = 0; 
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        reloadData();
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        selectedPath = f.toString();
        System.out.print(selectedPath);
        String filename = f.getAbsolutePath();
        selectedFileName = filename;
        //System.out.println(f);
        File file = new File(filename);
        
        try {
            BufferedReader br = new BufferedReader(new FileReader(file));
             
            String firstLine = br.readLine().trim();
            String [] columsName = firstLine.split(",");
            DefaultTableModel model = (DefaultTableModel)tableLop.getModel();
            model.setColumnIdentifiers(columsName);
            
            Object [] tableLines = br.lines().toArray();
            for(int i =0; i< tableLines.length; i++){
                String line = tableLines[i].toString().trim();
                String [] dataRow = line.split(",");
                model.addRow(dataRow);
            }
            
            //Get Last line
            if (tableLines.length > 1){
                int numLines = tableLines.length;
                currentSTT = getCurrentSTT(tableLines[numLines-1].toString());
            }else{
                currentSTT = 0;
            }

                
        } catch (Exception ex) {
            Logger.getLogger(DsSinhVien.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        filename = f.getAbsolutePath();
        txtImport.setText(filename);
       //Document_path.setText(filename);
       /////
               
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImportActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        System.out.print("closing");
        evt.getWindow().dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
       // System.out.print("closed");
        //this.setVisible(false);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DsSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DsSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DsSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DsSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DsSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbxMalop;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableLop;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtImport;
    private javax.swing.JTextField txtMSSV;
    // End of variables declaration//GEN-END:variables
}
